# ELIMINAMOS LA BASE DE DATOS SI EN CASO EXISTIERA
DROP DATABASE IF EXISTS SYSMDPN;

# CREAR BASE DE DATOS SYSMDPN
CREATE DATABASE SYSMDPN CHARACTER SET utf8mb4;

# UTILIZAMOS LA BASE DE DATOS
USE SYSMDPN;

# TABLA CARGOS
CREATE TABLE CARGO
(
	ID_CARGO		INT AUTO_INCREMENT NOT NULL,
    DESCRIPCION		VARCHAR(80),
    ESTADO			CHAR(1),
    
    CONSTRAINT PK_ID_CARGO PRIMARY KEY(ID_CARGO),
    CONSTRAINT UK_DESCRIPCION UNIQUE(DESCRIPCION)
);

# TABLA CRITERIOS
CREATE TABLE CRITERIO
(
	ID_CRITERIO		INT AUTO_INCREMENT NOT NULL, 
    DESCRIPCION		VARCHAR(80),
    ESTADO			CHAR(1),
    
    CONSTRAINT PK_ID_CRITERIO PRIMARY KEY(ID_CRITERIO)
);

# TABLA PERSONAS
CREATE TABLE PERSONA
(
	ID_PERSONA		INT AUTO_INCREMENT NOT NULL,
	APE_PATERNO		VARCHAR(80) NOT NULL,
	APE_MATERNO		VARCHAR(80) NOT NULL,
    NOMBRES			VARCHAR(80) NOT NULL,
    N_DNI			CHAR(8) NOT NULL,
    GENERO			VARCHAR(10) NOT NULL,
    CORREO			VARCHAR(80) NOT NULL,
    FECHA_NAC		DATE NOT NULL,
    TELEFONO		CHAR(9) NULL,
    CELULAR			CHAR(9) NULL,
    ESTADO			CHAR(1) NOT NULL,
    
    CONSTRAINT PK_ID_PERSONA PRIMARY KEY(ID_PERSONA),
    CONSTRAINT UK_N_DNI UNIQUE(N_DNI)
);

# TABLA ENTIDADES
CREATE TABLE ENTIDAD
(
	ID_ENTIDAD  	INT AUTO_INCREMENT NOT NULL,
    TIPO_ENTIDAD	VARCHAR(20) NOT NULL,
    RAZON_SOCIAL	TEXT NOT NULL,
    N_RUC			VARCHAR(11) NOT NULL,
    TELEFONO		VARCHAR(9) NOT NULL,
    DIRECCION		TEXT NOT NULL,
    CORREO			VARCHAR(80) NOT NULL,
    ESTADO			CHAR(1) NOT NULL,
    CONSTRAINT PK_ENTIDAD PRIMARY KEY (ID_ENTIDAD),
    CONSTRAINT UK_N_RUC UNIQUE(N_RUC)
);

# TABLA USUARIOS
CREATE TABLE USUARIO
(
	ID_USUARIO		INT AUTO_INCREMENT NOT NULL,
	ID_PERSONA		INT NOT NULL,
    ID_CARGO		INT NOT NULL,
    NOMBRE_USUARIO	VARCHAR(50) NOT NULL,
    CLAVE_USUARIO	VARCHAR(20) NOT NULL,
    ESTADO			CHAR(1),
    
    CONSTRAINT pk_ID_USUARIO PRIMARY KEY (ID_USUARIO)  
);

###ESTABLECEMOS LA RELACION ENTRE LA TABLA ESTUDIANTES Y LA TABLA PARTIDOS###
ALTER TABLE USUARIO ADD CONSTRAINT FK_USUARIO_PERSONA FOREIGN KEY(ID_PERSONA) REFERENCES PERSONA(ID_PERSONA);
###ESTABLECEMOS LA RELACION ENTRE LA TABLA ESTUDIANTES Y LA TABLA PARTIDOS###
ALTER TABLE USUARIO ADD CONSTRAINT FK_USUARIO_CARGO FOREIGN KEY(ID_CARGO) REFERENCES CARGO(ID_CARGO);

CREATE TABLE MODALIDAD
(
	ID_MODALIDAD	INT AUTO_INCREMENT NOT NULL,
    DESCRIPCION	VARCHAR(80) NOT NULL,
    ESTADO			CHAR(1),
    
    CONSTRAINT PK_ID_MODALIDAD PRIMARY KEY (ID_MODALIDAD)
);

CREATE TABLE REPRESENTANTE
(
	ID_REPRESENTANTE	INT AUTO_INCREMENT NOT NULL,
    ID_PERSONA			INT NOT NULL, 
    ID_ENTIDAD			INT NOT NULL, 
    CARGO_ENTIDAD		VARCHAR(80) NOT NULL,
    NACIONALIDAD		VARCHAR(80) NOT NULL,
    ESTADO				CHAR(1),
    
    CONSTRAINT PK_ID_REPRESENTANTE PRIMARY KEY (ID_REPRESENTANTE)
);

###ESTABLECEMOS LA RELACION ENTRE LA TABLA SOLICITUD Y LA TABLA TIPO_SOLICITUD###
ALTER TABLE REPRESENTANTE ADD CONSTRAINT FK_REPRESENTANTE_PERSONA FOREIGN KEY(ID_PERSONA) REFERENCES PERSONA(ID_PERSONA);
###ESTABLECEMOS LA RELACION ENTRE LA TABLA SOLICITUD Y LA TABLA PERSONA###
ALTER TABLE REPRESENTANTE ADD CONSTRAINT FK_REPRESENTANTE_ENTIDAD FOREIGN KEY(ID_ENTIDAD) REFERENCES ENTIDAD(ID_ENTIDAD);

CREATE TABLE EXPEDIENTE
(
	ID_EXPEDIENTE		INT AUTO_INCREMENT NOT NULL,
    ID_MODALIDAD		INT NOT NULL,
    ID_REPRESENTANTE	INT NOT NULL,
    ID_USUARIO			INT NOT NULL,
    N_EXPEDIENTE		TEXT NOT NULL,
    CONTEXTO			TEXT NOT NULL, 
    FECHA_APROBADO		DATE NOT NULL,
    MONTO_APROBADO		DECIMAL(10,2) NOT NULL DEFAULT '0.00',
    OBSERVACION			TEXT NOT NULL,
    SUMILLA				VARCHAR(80) NOT NULL,
    UBICACION			VARCHAR(80) NOT NULL,
    MOTIVO				VARCHAR(80) NOT NULL,
    PASES				INT NOT NULL DEFAULT '0',
    ESTADO				CHAR(1),
    
    CONSTRAINT PK_ID_EXPEDIENTE PRIMARY KEY(ID_EXPEDIENTE) 
);

###ESTABLECEMOS LA RELACION ENTRE LA TABLA SOLICITUD Y LA TABLA TIPO_SOLICITUD###
ALTER TABLE EXPEDIENTE ADD CONSTRAINT FK_EXPEDIENTE_MODALIDAD FOREIGN KEY(ID_MODALIDAD) REFERENCES MODALIDAD(ID_MODALIDAD);
###ESTABLECEMOS LA RELACION ENTRE LA TABLA SOLICITUD Y LA TABLA PERSONA###
ALTER TABLE EXPEDIENTE ADD CONSTRAINT FK_EXPEDIENTE_REPRESENTANTE FOREIGN KEY(ID_REPRESENTANTE) REFERENCES REPRESENTANTE(ID_REPRESENTANTE);
###ESTABLECEMOS LA RELACION ENTRE LA TABLA SOLICITUD Y LA TABLA TIPO_SOLICITUD###
ALTER TABLE EXPEDIENTE ADD CONSTRAINT FK_EXPEDIENTE_USUARIO FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO);

CREATE TABLE DETALLE_EXPEDIENTE
(
	ID_DETEXPEDIENTE		INT AUTO_INCREMENT NOT NULL,
    ID_EXPEDIENTE			INT NOT NULL,
	FECHA_DERIVACION		DATE NOT NULL,
	AREA_COMPETENTE			VARCHAR(80),
	FOLIOS					INT NOT NULL,
	OBSERVACION				TEXT,
	NUEVO_ESTADO			CHAR(1),
    
    CONSTRAINT PK_ID_DETEXPEDIENTE PRIMARY KEY (ID_DETEXPEDIENTE)
);

###ESTABLECEMOS LA RELACION ENTRE LA TABLA ESTUDIANTES Y LA TABLA PARTIDOS###
ALTER TABLE DETALLE_EXPEDIENTE ADD CONSTRAINT FK_DETALLE_EXPEDIENTE_EXPEDIENTE FOREIGN KEY(ID_EXPEDIENTE) REFERENCES EXPEDIENTE(ID_EXPEDIENTE);


# TABLA TIPO_SOLICITUD
CREATE TABLE TIPO_SOLICITUD
(
	ID_TIPO			INT AUTO_INCREMENT NOT NULL,
    DESCRIPCION		VARCHAR(80),
    ESTADO			CHAR(1),
    
    CONSTRAINT PK_ID_TIPO PRIMARY KEY (ID_TIPO)
);

# TABLA SOLICITUD
CREATE TABLE SOLICITUD
(
	ID_SOLICITUD 		INT AUTO_INCREMENT NOT NULL,
    -- ID_PERSONA		INT NOT NULL,
    -- ID_ENTIDAD		INT NOT NULL,
    ID_REPRESENTANTE	INT NOT NULL,
	FECHA_ING			DATE NOT NULL,
    SERIE_SOL			CHAR(10) NOT NULL,
    CONTEXTO_SOL		TEXT NOT NULL,
    ID_TIPO				INT NOT NULL,
    ESTADO				CHAR(1),
    
    CONSTRAINT PK_ID_SOLICITUD PRIMARY KEY (ID_SOLICITUD) 
);

###ESTABLECEMOS LA RELACION ENTRE LA TABLA SOLICITUD Y LA TABLA TIPO_SOLICITUD###
ALTER TABLE SOLICITUD ADD CONSTRAINT FK_SOLICICTUD_TIPO FOREIGN KEY(ID_TIPO) REFERENCES TIPO_SOLICITUD(ID_TIPO);
###ESTABLECEMOS LA RELACION ENTRE LA TABLA SOLICITUD Y LA TABLA REPRESENTANTE###
ALTER TABLE SOLICITUD ADD CONSTRAINT FK_REPRESENTANTE FOREIGN KEY(ID_REPRESENTANTE) REFERENCES REPRESENTANTE(ID_REPRESENTANTE);


CREATE TABLE TIPO_EJECUCION
(
	ID_TIPO_EJECUCION	INT AUTO_INCREMENT NOT NULL,
    DESCRIPCION			VARCHAR(50) NOT NULL,
    ESTADO				CHAR(1),
    
    CONSTRAINT PK_ID_TIPO_EJECUCION PRIMARY KEY (ID_TIPO_EJECUCION)
);

CREATE TABLE OBRA
(
	ID_OBRA				INT AUTO_INCREMENT NOT NULL,
    ID_EXPEDIENTE		INT NOT NULL,
    NOMBRE_OBRA			TEXT,
    FECHA_INICIO		DATE NOT NULL,
    FECHA_FIN			DATE NOT NULL,
    TOTAL_DIAS			INT NOT NULL,
    MONTO_APTO			DECIMAL(10,2) NOT NULL DEFAULT '0.00',
    FINANCIA_UNO		CHAR(1) NOT NULL,
    FINANCIA_DOS		CHAR(1) NOT NULL,
    ID_TIPO_EJECUCION	INT NOT NULL,
    ESTADO				CHAR(1),
    
    CONSTRAINT PK_ID_OBRA PRIMARY KEY (ID_OBRA)
);
###ESTABLECEMOS LA RELACION ENTRE LA TABLA SOLICITUD Y LA TABLA TIPO_SOLICITUD###
ALTER TABLE OBRA ADD CONSTRAINT FK_OBRA_EXPEDIENTE FOREIGN KEY(ID_EXPEDIENTE) REFERENCES EXPEDIENTE(ID_EXPEDIENTE);
###ESTABLECEMOS LA RELACION ENTRE LA TABLA SOLICITUD Y LA TABLA REPRESENTANTE###
ALTER TABLE OBRA ADD CONSTRAINT FK_OBRA_EJECUCION FOREIGN KEY(ID_TIPO_EJECUCION) REFERENCES TIPO_EJECUCION(ID_TIPO_EJECUCION);


CREATE TABLE MOVIMIENTO_OBRA
(
	ID_MOBRA			INT AUTO_INCREMENT NOT NULL,
	ID_OBRA				INT NOT NULL,
    NOTIFICACION		CHAR(1),
    OBSERVACION			VARCHAR(80),
    ESTADO_NOTIFICAR	CHAR(1),
    TIPO				CHAR(1),
    MOTIVO_SUPER		VARCHAR(80),
    FECHA_INICIO		DATE NOT NULL,
    FECHA_FIN			DATE NOT NULL,
    OBSERVACION_GENERAL	TEXT,
    INTEGRANTES			INT NOT NULL DEFAULT '0',
    
    CONSTRAINT PK_ID_MOBRA PRIMARY KEY (ID_MOBRA)
);

###ESTABLECEMOS LA RELACION ENTRE LA TABLA SOLICITUD Y LA TABLA TIPO_SOLICITUD###
ALTER TABLE MOVIMIENTO_OBRA ADD CONSTRAINT FK_MO_OBRA_OBRA FOREIGN KEY(ID_OBRA) REFERENCES OBRA(ID_OBRA);

CREATE TABLE ASIGNAR_PARTICIPANTES
(
	ID_ASIGNAR			INT AUTO_INCREMENT NOT NULL,
	ID_MOBRA			INT NOT NULL,
    PARTICIPANTE		TEXT,
    N_DNI				CHAR(8),
    
    CONSTRAINT PK_ID_ASIGANR PRIMARY KEY (ID_ASIGNAR)
);

###ESTABLECEMOS LA RELACION ENTRE LA TABLA SOLICITUD Y LA TABLA TIPO_SOLICITUD###
ALTER TABLE ASIGNAR_PARTICIPANTES ADD CONSTRAINT FK_ASIGANR_MOV FOREIGN KEY(ID_MOBRA) REFERENCES MOVIMIENTO_OBRA(ID_MOBRA);

CREATE TABLE MATRIZ
(
	ID_MATRIZ		INT AUTO_INCREMENT NOT NULL,
    ID_OBRA			INT NOT NULL,
    N_RIESGO		CHAR(4) NOT NULL,
    DESCRIPCION		VARCHAR(80) NOT NULL,
    ESTRATEGIA		VARCHAR(50),
    ACCIONES		VARCHAR(50),
    ASIGNACION		VARCHAR(50),
    
    CONSTRAINT PK_ID_MATRIZ PRIMARY KEY (ID_MATRIZ)
);

###ESTABLECEMOS LA RELACION ENTRE LA TABLA SOLICITUD Y LA TABLA TIPO_SOLICITUD###
ALTER TABLE MATRIZ ADD CONSTRAINT FK_MATRIZ_OBRA FOREIGN KEY(ID_OBRA) REFERENCES OBRA(ID_OBRA);