USE SYSMDPN;

DELIMITER $$
CREATE TRIGGER TRI_AUMENTAR_PASES
AFTER INSERT ON detalle_expediente FOR EACH ROW
BEGIN
Update EXPEDIENTE set EXPEDIENTE.PASES = EXPEDIENTE.PASES + 1
where  EXPEDIENTE.ID_EXPEDIENTE = NEW.ID_EXPEDIENTE;
END
$$


DELIMITER $$
CREATE TRIGGER TRI_AUMENTAR_INTEGRANTES
AFTER INSERT ON asignar_participantes FOR EACH ROW
BEGIN
Update MOVIMIENTO_OBRA SET MOVIMIENTO_OBRA.INTEGRANTES = MOVIMIENTO_OBRA.INTEGRANTES + 1
where  MOVIMIENTO_OBRA.ID_MOBRA = NEW.ID_MOBRA;
END
$$